
# Default
spring:
  profile:
    active: local

### LOCAL
---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjdehddnr1@
  jpa:
    show-sql: true

### TEST
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2